# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vendaspassagens.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vendaspassagens.proto\x12\x0fvendaspassagens\"9\n\x08Passagem\x12\x0e\n\x06origem\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"6\n\x08Resposta\x12\x17\n\x0f\x64isponibilidade\x18\x01 \x01(\x08\x12\x11\n\tcategoria\x18\x02 \x03(\t2e\n\x0fVendasPassagens\x12R\n\x18VerificarDisponibilidade\x12\x19.vendaspassagens.Passagem\x1a\x19.vendaspassagens.Resposta\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vendaspassagens_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PASSAGEM._serialized_start=42
  _PASSAGEM._serialized_end=99
  _RESPOSTA._serialized_start=101
  _RESPOSTA._serialized_end=155
  _VENDASPASSAGENS._serialized_start=157
  _VENDASPASSAGENS._serialized_end=258
# @@protoc_insertion_point(module_scope)
