# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vendas_aereas_pb2 as vendas__aereas__pb2


class VendasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarDisponibilidade = channel.unary_unary(
                '/vendas_aereas.Vendas/VerificarDisponibilidade',
                request_serializer=vendas__aereas__pb2.RequisicaoDisponibilidade.SerializeToString,
                response_deserializer=vendas__aereas__pb2.RespostaDisponibilidade.FromString,
                )


class VendasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerificarDisponibilidade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VendasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarDisponibilidade': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarDisponibilidade,
                    request_deserializer=vendas__aereas__pb2.RequisicaoDisponibilidade.FromString,
                    response_serializer=vendas__aereas__pb2.RespostaDisponibilidade.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vendas_aereas.Vendas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Vendas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerificarDisponibilidade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vendas_aereas.Vendas/VerificarDisponibilidade',
            vendas__aereas__pb2.RequisicaoDisponibilidade.SerializeToString,
            vendas__aereas__pb2.RespostaDisponibilidade.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
