# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vendas_aereas.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vendas_aereas.proto\x12\rvendas_aereas\"h\n\x19RequisicaoDisponibilidade\x12\x14\n\x0c\x64\x61ta_partida\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61ta_retorno\x18\x02 \x01(\t\x12\x0e\n\x06origem\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x04 \x01(\t\"Z\n\x17RespostaDisponibilidade\x12\x12\n\ndisponivel\x18\x01 \x01(\x08\x12+\n\tcategoria\x18\x02 \x01(\x0e\x32\x18.vendas_aereas.Categoria*>\n\tCategoria\x12\r\n\tECONOMICA\x10\x00\x12\r\n\tEXECUTIVA\x10\x01\x12\x13\n\x0fPRIMEIRA_CLASSE\x10\x02\x32v\n\x06Vendas\x12l\n\x18VerificarDisponibilidade\x12(.vendas_aereas.RequisicaoDisponibilidade\x1a&.vendas_aereas.RespostaDisponibilidadeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vendas_aereas_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATEGORIA._serialized_start=236
  _CATEGORIA._serialized_end=298
  _REQUISICAODISPONIBILIDADE._serialized_start=38
  _REQUISICAODISPONIBILIDADE._serialized_end=142
  _RESPOSTADISPONIBILIDADE._serialized_start=144
  _RESPOSTADISPONIBILIDADE._serialized_end=234
  _VENDAS._serialized_start=300
  _VENDAS._serialized_end=418
# @@protoc_insertion_point(module_scope)
