# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vendas.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvendas.proto\x12\x06vendas\"X\n\x0fPassagemRequest\x12\x10\n\x08\x64\x61ta_ida\x18\x01 \x01(\t\x12\x12\n\ndata_volta\x18\x02 \x01(\t\x12\x0e\n\x06origem\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x04 \x01(\t\">\n\x10PassagemResponse\x12\x17\n\x0f\x64isponibilidade\x18\x01 \x01(\x08\x12\x11\n\tcategoria\x18\x02 \x01(\t2c\n\x10PassagensService\x12O\n\x18VerificarDisponibilidade\x12\x17.vendas.PassagemRequest\x1a\x18.vendas.PassagemResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vendas_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PASSAGEMREQUEST._serialized_start=24
  _PASSAGEMREQUEST._serialized_end=112
  _PASSAGEMRESPONSE._serialized_start=114
  _PASSAGEMRESPONSE._serialized_end=176
  _PASSAGENSSERVICE._serialized_start=178
  _PASSAGENSSERVICE._serialized_end=277
# @@protoc_insertion_point(module_scope)
