# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vendaspassagens_pb2 as vendaspassagens__pb2


class VendasPassagensStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarDisponibilidade = channel.unary_unary(
                '/vendaspassagens.VendasPassagens/VerificarDisponibilidade',
                request_serializer=vendaspassagens__pb2.Passagem.SerializeToString,
                response_deserializer=vendaspassagens__pb2.Resposta.FromString,
                )


class VendasPassagensServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerificarDisponibilidade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VendasPassagensServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarDisponibilidade': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarDisponibilidade,
                    request_deserializer=vendaspassagens__pb2.Passagem.FromString,
                    response_serializer=vendaspassagens__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vendaspassagens.VendasPassagens', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VendasPassagens(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerificarDisponibilidade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vendaspassagens.VendasPassagens/VerificarDisponibilidade',
            vendaspassagens__pb2.Passagem.SerializeToString,
            vendaspassagens__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
